apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 1h
  url: https://charts.longhorn.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: "1.12.1" # Adjust to your target Longhorn version
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
  values:
    # Essential for GitOps automation to prevent hanging upgrade hooks
    global:
      preUpgradeChecker:
        job:
          enabled: false
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultDataLocality: ~
      replicaSoftAntiAffinity: ~
      replicaAutoBalance: ~
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      upgradeChecker: ~
      defaultReplicaCount: 3
      # storageNetwork: longhorn-system/longhorn-network
      guaranteedInstanceManagerCPU: 15

    persistence:
  # Default storage class
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4

    # Resource limits
    longhornManager:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi

    longhornDriver:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi

    # Enable the UI
    longhornUI:
      replicas: 2