apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 1h
  url: https://charts.longhorn.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h

  chart:
    spec:
      chart: longhorn
      version: "1.12.1"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo

  values:
    preUpgradeChecker:
      jobEnabled: false

    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultReplicaCount: 3
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      guaranteedInstanceManagerCPU: 15

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4

    longhornManager:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi

    longhornDriver:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi

    longhornUI:
      replicas: 2