apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - namespace.yaml
  - vaultwarden-db-secret.yaml
  - vaultwarden-db-url.yaml
  - postgres-cluster.yaml
  - vaultwarden-helmrepository.yaml
  - vaultwarden-helmrelease.yaml
  - gateway.yaml
  - httproute.yaml
  - https-redirect.yaml
  - vw-secret.yaml