apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-postgresql
  namespace: vaultwarden
spec:
  instances: 2 # Set to 2 or 3 for high availability (primary + standby replicas)
  
  # Storage configuration
  storage:
    size: 5Gi
    storageClass: local-path # Adjust to your RWO storage class

  # Database initialization defaults
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-db-secret # Secret created by CNPG holding database credentials

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: vaultwarden-b2