apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-postgresql
  namespace: vaultwarden
spec:
  instances: 2 # Set to 2 or 3 for high availability (primary + standby replicas)
  
  # Storage configuration
  storage:
    size: 5Gi
    storageClass: local-path # Adjust to your RWO storage class

  # Database initialization defaults
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-db-secret # Secret created by CNPG holding database credentials

  backup:
    barmanObjectStore:
      destinationPath: "s3://vwdb-backup/"
      endpointURL: "https://s3.us-east-005.backblazeb2.com" # Prefix your B2 endpoint with https://
      s3Credentials:
        accessKeyId:
          name: backblaze-b2-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-b2-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d" # Automatically prune backups older than 30 days