apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:VLiIzJlk63TFXYH1CPNVr7ZUKPjzoeAVKOczsisZ44sovM8XMb1GnW6Tsf4=,iv:uN95kBaetBQmFyW4H8pAcu96V3PYxXCE26utIbaiKHI=,tag:bLp0qEGZct8EcG8GwDg3sw==,type:str]
    postgres-password: ENC[AES256_GCM,data:GmrhPrz7YqjFJc50QHy2Zw==,iv:HI2CoHcR9pXp9zLjT7e6X7YIsr6nOvFHlfVUibFEbqM=,tag:a9BfcH1qm3QhSQNvazJPag==,type:str]
    username: ENC[AES256_GCM,data:CFKnxqhlODx/3FUPVSkIdg==,iv:zopZQhmg9LBK+IbNUXfUf46xyDWKJUyZf5ER9V4Q0u8=,tag:q5xBfbLdikdttP9PhG0s+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV2xxNlZuU3pJcXVPMnFx
            U0drZ1FOdExBZWQ0VlhoS3J6VmRuVGMwRUhzCkdTVmYzRVQ4RTd4b0pYdnJRWXd2
            RnZxQTNZK2thLzRiYStHSmlTYy85dkUKLS0tIGVmM25PTXRKTE85R25iQW9BWUxR
            b0pqSmUrcnRhZDRmL1RtalVCMmFPQ3MK6SnxOPIcsM9aWkoV795yGYbnw5is96s7
            VJiy7TbreGnQ4qmw7awvw9+z4lQKS5C6p6g/awuaFjcPEJcpFI0SMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T06:56:26Z"
    mac: ENC[AES256_GCM,data:l/7gsimtwyywR+Cz/DJQ++x/ctcjIid78qYfkyfsaCJoBcqzo7FPx8M2tOc0x/kekF34+9GnG4Q4fTWx7pGeovgkv9rSrltFrT37kgIxRPvoMZ5+EvD581Up9gqBcjXHGqV6YgXEJFt5ekao99Tn87lj+QDCuLr0JOImM+fj7Do=,iv:x+OafuCn5uP10SxgTOGrIQMn8EuFEeFyMQmo8KTezYQ=,tag:22jdZf5AcKDHs4mVTmH2+w==,type:str]
    version: 3.13.2
