apiVersion: v1
stringData:
    pgpassword: ENC[AES256_GCM,data:3iytz2y4CVwYTIOuEAInkA==,iv:BCXvND6cTaoFwz1W2TgMjG5DlF2p7OzFY+MUflHmk5w=,tag:eYTQDQJZkxyXtiIs9CsjoQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:mHLkkJZifqjgyWV5ILQBEA==,iv:5IVf0M/+Ufl4SDL+8NJeqS6+p4K2LC3po3LmL9zGn5s=,tag:qNgqCJqL5KGI/BHqXTOuKw==,type:str]
kind: Secret
metadata:
    name: vaultwarden-db-secret
    namespace: vaultwarden
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UmFtbHI4NlppVmJlSlIx
            dG5OcnNmRnk3SVczbHhXTWZ1ZlVmYVRHZlNzCkpiOEU1UlFLYXhtZ3RyL2Nyd3o1
            aXhXcm02MGNlMTdCMGkyYVBXbzZHSk0KLS0tIDE0SjE1YnFScjVvbjlzSTJNSHZH
            dWRNbndNNENUU3FIblcvem1xenVVdFUKsOQoo9cz9oshD2lNB4qwFPyHDWUfM0mx
            qIzeMobSSjM83K9Jd9gXf2vcK/oKeDu+yeiVok9ameYj7P07WlhjGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T01:58:35Z"
    mac: ENC[AES256_GCM,data:4W2M/knbYFHQEiqNJNZvt9uTS8xJ9Mt5/LF28b7Fk5F45Egv4fOrX6bSY3QyOU/XoMQZ3LJbn55iVPjFeT5zi6WKxCltlKo2A0u1S9zQhMmreioh1ZzRyYBtqcaKYjXNjTrmw3c6uKUoh54Fdg0twcr1acB1nszi9QhfN1VhgH0=,iv:OFQxOfZAGMUN/oi58zem8Nk7xkmL+hSzynnILKzjUO0=,tag:IMfTBV8nER2kiETnBDk4jQ==,type:str]
    version: 3.13.2
