apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 30m

  # dependsOn:
  #   - name: vaultwarden-postgresql

  chart:
    spec:
      chart: vaultwarden
      version: "0.43.x"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: vaultwarden
      interval: 1h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: vaultwarden
    domain: "https://test-vaultwarden.tmatthews.casa"

    image:
      tag: "1.34.3"

    websocket:
      enabled: true

    webVaultEnabled: true

    database:
      type: postgresql
      existingSecret: vaultwarden-db-secret
      existingSecretKey: uri
      connectionRetries: 30
      maxConnections: 10

    adminToken:
      existingSecret: vw-secret
      existingSecretKey: ADMIN_TOKEN

    storage:
      data:
        enabled: true
        size: 10Gi
        class: ugreen-nfs-sc
        accessMode: ReadWriteOnly
        dataDir: /data

    service:
      type: ClusterIP

    ingress:
      enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi