apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:BlcnLcDNW+qFV3E/mR1fXt2VNwrdTwaogRNNWIuo7FE=,iv:9jOILVilkRbYkC5oEYA0agnIt+Fcv5BU9nkvX5AaH9s=,tag:aMBHXvmSwnoakJElKI+aKQ==,type:str]
    username: ENC[AES256_GCM,data:Y++8/WwOiS92f7I=,iv:6Cf5OzmC5qmQMafvRSQ0sGmWO1CBtp9nq6ED9Wev08E=,tag:1fzpDUMn5IdvPmTgOgsylw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcEcyMVJiWkxiMWxHaFoz
            YjloNzFmbVV1RUNlemp2TTR3OGlXWnJJcmtJCnZCbFRhcjJGTCtXWUlSL1IzaWx2
            bmJvcUR0cmhpbWVMRlc1VFAva0g0NTAKLS0tIHVMVDZWNXZEQm1obXlOTDd3Tkdq
            SXNlV0c0UDZvdjhCZWRML0dEVDA4R1kKUBrKjFGzqXEWgZDDW/q0xlpwEAmBfkCe
            lgoV8loK882tJbctGfHiI+tt5SAYbbGMWa71xjG+RRIdOt6H2IyGhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T07:37:19Z"
    mac: ENC[AES256_GCM,data:IFfLceUHvN1yfEl+iyNcPtTUQYqQg8rXWiFrOeHSYPadLS7wAX+iev1eER50uG5d2/MpkcZnFHQmL13sZCRnrZVPVkb42kear79VHN3mv8sOKm+x8TO1YrhhrSVslNOJaMSXAgXEi0FCLBY8Fgcg0NWlq46EDJREmR7DROxwOYs=,iv:Z7MfG8WZPfwBZele+Vq586RAwKs5ofGd5onalM+k9xc=,tag:DDkv96HUh8rGvAODfWrZAQ==,type:str]
    version: 3.13.2
