apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-url
    namespace: vaultwarden
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:H7AjybX9A/MmxniQnVyt/yBFqnNTf5B4xdUlIOSo2rIqwl2Y1diaMVwPAJwFtYk/XUyezcC+zgyAAku3OtjJqiTwHd3lOBU6eq6uJjaoBkR+FKD1/iDffDpNorcT5BbYWLe2+xW/ncLy644gxKss9Tw3ytqNGOqloUfXMoTmhmprkg==,iv:k6lXdcRJZ7oLEO7Jmwm48KxKjvT6Y7Or+LfFfNNjs3w=,tag:AUmsypBhVrKX2QheUsEdIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubzdUaVFlWk9xVkluc2ZL
            eW83TElBay8yNS9Tb1pjRU42V0I0R1Y5Z0E0ClE0NnpsK0laSnpaK0k3bVFwbytr
            c2JFRWRESDNiYjlXYjl6c3dHVUtWZkEKLS0tIFozMEF2dUJlT3p3WVVDNUxGT3Na
            Z0VlNnN6N1kvb2hrQjNtdlY3aWZVQlEKz2ErWES5vSLZbPgQlOqxC/oElRL2Onsg
            6iBr3hIFDnadg4d7xhg/9EmbiJXxj7RQChZFF3ymwK0PxLB5iDm24A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T06:55:01Z"
    mac: ENC[AES256_GCM,data:mTkkIN2WMyfKq2/qwSaoIJXmr/WC9EJR+GTfyMs3i658NAC7PkqXzIqiwk1NxVrERuj59Ky5pugYE8iY3E5rLoS32TenFlC8bZxDowE0Q9tNSC0TrxqRVEaOIhP+rEhg7HOTHmv8LIAiPaDbWluo7TC1HJRr22q8Vn1NUNiHk0U=,iv:aJZSWhHDrobr+8IUIKQP3ycPQz98tBoMWsfL9gSDIxg=,tag:nZWthzfbsZxFR4etvtJc3w==,type:str]
    version: 3.13.2
