apiVersion: v1
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:alqXLh82CsW7x44W49DIaMdfWdYZL3Jrr4VblmsTWcoNpxxuio44HKvAedpMW79xPgTQV2ySkCS+wDL2ThYyht20iZLd/nZRA2nKpRxy6aenCwRoRPPdXLY+Lf3Oi7Q9i4Uww+ff9RK8dP4jfY4tcGnhyxoqRn7qbj4LVtCmm5NT6B5h2oaYEEjbvxydvYqfX+2hiPteQ4yZgbVeMWoXog==,iv:1peBFdDCZ1H/29fcerixuDWLVX+BG7DnHQ194JI6lxg=,tag:lT+pbIBuDioVBuAj8COmvQ==,type:str]
    user: ENC[AES256_GCM,data:8/eoa67PN3E=,iv:5LRi5twFN/D5780HhQyp4xv5P9qT47f8As6mj1RtZWA=,tag:+ZW/v3JMF8NRS7jlt1r8Bw==,type:str]
kind: Secret
metadata:
    name: vw-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cjhQNHF3TW9oNzc3ejlz
            RjBtL3FIRWhlU2tKelRhN0VMUmFPQjFrSGdnCm5iZXJKa3JTUFdWWXc4YytOUjhi
            WHJjcUd5L01vV0x6aVZoMWIxNXFOTXcKLS0tIEZIU1NJM0dOeVcydEYzeFpFVTR2
            a1ZFdys1SGJEZ2lGR002djBsSlpmRFkKXK8izyHggBQAQGADAc3rZT9uCKILpJYQ
            vM0ZZ5saVI1Bo4HjHfLb2MzYG5fMY3a2lVl8q2fuTh27Bsa24oD1Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T03:55:48Z"
    mac: ENC[AES256_GCM,data:4vsY7TLjY9dp7xg+udMUmmgFFY7lqiLJC9cbd8aXveiMtQk38BNHb5EYj6lSJz1P7uC3tIUXgXKhuK57Vesmns0MCvexjKFFlC7GKTUBu9Mo0aofTfAsiiQEtLZ4L2SCNAXt68i/KsgYAw8AQqIbzi4kE0Mz5mHRHROJ0rPpjLY=,iv:4G6nBMwW7zPS602xS9LnZZnO1kUn06aKY8uCbOHVt3U=,tag:9XE3A9SScd3jMgfKdOnKBg==,type:str]
    version: 3.13.2
