apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:7OJCjA2smsBXoantObolFJMznyNrtHlvN5at6BDOka4Ge82rHZrwcJkZBro8fWKhAPoAFVg1tDmYrcCuiVucroH+Ku1IdjUYVQmF75LALupqUiofSXIvUsZvAcwmQ3wkDTdRFSkGjlZNBvDT6vx66RrGV4b8fA==,iv:kkS0u1pSPaudXOkj6Lw011u5qL/8AS17nGucRfnsOrc=,tag:OuwZKe1kcJQQFy5n1bjcZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiLzlveHloYVZiNHR1bGdO
            cmg2OTRlQjh5VldBUmg2N0VnUVhHNURDTFJNCkFWQTJ3M3ZXbXdqQ1NuRHJZWStt
            VWRWYXhXZ0xIcU9peFNXZUlzQzdYUUUKLS0tIHNRajFyUDJzc3ZPYU53aUlOSDBU
            WHkrc000aGV2T3Y4L1RLalpUK1VBVUEKMqjbnCkFEvJen6ZSmUFgDqq22ngGj2qJ
            +9w3psWYrO3AoemgV1Cn3Jmq4rBykvjRxvhrEvMXBzxvzoMWFpdGTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T05:04:44Z"
    mac: ENC[AES256_GCM,data:Xguk7VmW2PVbHGvSV2641EqfoCl0vlAwNTS5NnhNu4pyePysOrSxWRi7VmIYr1H08vWmgmOyr4p2MCNzI3wkNIRjKfvWt85LC3sgTg2aKUi9F4PF0GtKZNPo9DEfHYcLC8lCo6xyVZp1so5cDIiUAMedP61SnxLGYCynAoZoaFg=,iv:YgVnAdnhMBdVkcdmkLKEuu+ZJ/8z/wNPmZGTw0CtRR8=,tag:cSEwQZv7TdnZkG51HXupgA==,type:str]
    version: 3.13.2
