apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:KGqAR8hbS3IZnXpUDN6gET28GsTD46quiVf9SqhbSL3xs5mI3ITH+GcpXZZOOOV1wJzot5VtxtR9hqnUSvLcphbQuchuj+SI7MVSPCK2McjEt3wtMiLDThE52TvEF3aGlEiiC8XSMMx7QN+yYqXsh6wiYPZbUg==,iv:hCfOk0FV6FFn7Erd2p3Kr50z7kPa44NtynFB0FlWzQY=,tag:abHElsTyY6mpsxJPTbk48g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlVjenFIU1dlVWRvbnhE
            N0h1OTNwc1o0cVJxdTV0R2w5THcwM0ZIdHlFCmxiVDRpWlZFQ3hDdWdVbWgwRU9X
            bjYwamU0SmwvaG9ONUR2WVMyVGN0TlEKLS0tIFc5alNlUmdFVk1IWEwzQWJTMlJt
            NFhKWUFwdTZZd0NEQ0duNmtSTFN0U2cKFbT4pMuJrt0vak3y9nJSKgZeNDu+cbuR
            vT8gsPMLljTOZWkAFAXKq1wDiyZxcwkVtoC3OCRQ5VkcvOjms4Nnzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T04:09:58Z"
    mac: ENC[AES256_GCM,data:SueXPdJDrQV/KXteFnKROoDrtEzPrj5OirDrmN/IbqzmzThBE3CZ1TQWUWSdddNUEbHiQlwtUDkyD8v3e/12ZhUWpvrz3LowapV3IcxrqPkTmcr/IsjvVf6sHcWG7oKCgL/gYSzdCENbEt8XHYR332dekE9iUhXy3SIN7iJ8fAM=,iv:gUhdM3fIISLyQYgLQdg31misCTmcnB5SPyWO/Xik+G8=,tag:HGRtM1/RdTR4bblzZWe/7A==,type:str]
    version: 3.13.2
