apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiMTRjNDBjNDhlZmM0M2FmOWI5YjhmMWIxOWViNGQ2ZjUiLCJUdW5uZWxTZWNyZXQiOiJ1VGk0Ym4zZmx1OTZtNUhSR0JSWGhmRkNsN1ZtSnFRSVAwd2ZUVm5mdHFrPSIsIlR1bm5lbElEIjoiMDYxZTVlZmUtNWZjNy00OGFjLWFmZTctMzkzNTVmMjY1MjVhIiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  name: tunnel-credentials
