apiVersion: v1
kind: Secret
metadata:
    name: rfc2136-keys
    namespace: external-dns
type: Opaque
stringData:
    rfc2136-tsig-keyname: ENC[AES256_GCM,data:rknmr0iTzvS4iBHY,iv:vtTqAYXviNNzptGgmBIIeqgdx4zUA25UYNWvS4FCjF4=,tag:QIDWSE3l5cLC5lAkUe+hxA==,type:str]
    rfc2136-tsig-secret: ENC[AES256_GCM,data:oW/XOdSaogzcG9gVZNXndr+cWKRmYyWRJjXsj+JtXrW0ypUqVrOv14bRjak=,iv:h38z3yi61yGt/e0RGs0wRaTCkRuz9ThgaFNr2l8Nhg0=,tag:480bWEr+R3akaxd1Oyf4UQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWdQQytwTFhGRHNtZG1s
            RTc1bWFRSm9HL1JMZVVXZTFkMmlTd0cwQkZNCkRHV2c3SC93UU9EMm16Q1o0bDQr
            c3pXT2wzUndVRHZTSnVIcG1DM0U2c1EKLS0tIGZ5ek1aaTBTSXVhTEdSbmYyWEkr
            RUorbDJpRUdpZ01SZHpGQjd0MWtkNE0KjaCdWbL5ZtwOUab8Vk/793Lwlmtvg3vO
            BH0hZ5AsujftZdu0sOVLqJOMgTyKrB5XY57CtowuX9EDiEU8B7SLwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T02:36:31Z"
    mac: ENC[AES256_GCM,data:T0Uj3uag+m+wVXwnlMRH6bhDYUjvukzF94UsBPSeutQxmM3yHVnY/VpuODaJrEDQ72bmbOjW7X7SG0U4sMt3H58ZbRkZgf2cam+OkZb3q4ZJibsNeDID5WRM4EHmU7PFPbo8hfu1DMZHIJE8cYJN+deLLFuCCPIGhTq18p4Ze7k=,iv:Vc/HYiTc/gTZlR8E97jb9rkz/p5gJG844VATtp4XppM=,tag:fX6tGfo5tG1Ry0i258lkiQ==,type:str]
    version: 3.13.2
