apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-b2-backup
spec:
  cluster:
    name: vaultwarden-postgresql
  schedule: '0 0 20 * * 1,3,5'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  suspend: false