apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:8aEvnsuKZ1LQ6BPc1k9bU4WBCxN1mbLyXf9asF2W2ig=,iv:uxK/tRwVohxrhn5W2c8y5RoGTEvlC0iY5VPWIOdmPwk=,tag:tirsCO2Fqa9/UZQRVcwxpQ==,type:str]
    username: ENC[AES256_GCM,data:+Co1hkZFZzCxiAY=,iv:cuIrqEwfW0a0P3G0ir/DdlZt7EwpqHNDZ50zqReArqc=,tag:QmLrLUvQy1iRDl2kWRQwJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdmY2T015YmRhdU12RzRx
            NXI0Uy9MTkJtVFFLanMyemZkZndhY2lKSTJrCmJ4UENLWGpuSTljZTF2a0ZQMmQ4
            YzVVUTFzSHdtOUJpbG9ickxTWlgvYU0KLS0tIGVlMlhaWkM1aitXWTVXOWZwVlp2
            aUpmWDVCNitheUUrMmxVOWtOWWJySjAKhGUp5nPGTujYkI0INuTAW1yLt69tFYz3
            EzooB09eouOk9BmR9059NT2VIwE4wlMWguMMbt7kQPGitYy/jnasvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T02:17:18Z"
    mac: ENC[AES256_GCM,data:1/YwDbCYjBJ8mo9LWiunUUpST9W5qBYWfChnzoEWxJLWij5m6DmRYoQX/KtSldP+1daPG6bJKtNyb/+6hRHBGq4uiyAhXZV/Tyv+Mt92kSUkibfLbmoAQk3uIS82m3byQqbD8ksCPTBqEcEmlXXUCZV5DaXkv69+/ARarHED7Sg=,iv:7oaKIU2L1+wkVJxFCadf1SOtuaFVkAcyBKo12FqTjkI=,tag:soUeNnD8PTBS6Y8pykTCgg==,type:str]
    version: 3.13.2
