apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:oE4eZ8Pgud3PvhTkxbe1mS5zBwCzNjIGOmzbOfy7ohyAUlt8XitTxnkjuBRBCvnoI3QxweYzsSiBZJTGfMk9xeM3ZZ4ukAhE8wNl6DFmeK+J6hkOqQmHo+4/3ahhOXjbDN+uBKEkJs8tU8Uf86laAQaWs8bdQw==,iv:EN+cs2pehV3ue76MgXwngpADAU0q25pHkbj0Vdt7u/c=,tag:vdvPXU/JWoeKSBXrodg65A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VkN6T3lVeEl2RnprUW5a
            U2ZIYnN6ajV3NXlFNDRKRWpUcms0M2Vmc0RBCk9IZDE5N0RMell0bnZaaUVNT2U4
            ZERtejNibjZYV1ozOGVZN2xCcUE1aFUKLS0tIFh1TFpSY05xekhMdVMwai9ZYUtY
            VDV6OHVEbGdxVTkzaVhzMjd6OERja28Ky817L0c6xL670O1DuXsfZY8YW6idKdvi
            4kvB5W1RUKzPGSDpa1e8NgMxzFaCGJRUfGbjTNlaUk/7bxhd43MAZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T02:17:46Z"
    mac: ENC[AES256_GCM,data:P9EqIj0WQtinjZTfeGsM90i6Q7Ckd1lFlIU/oZcJA/kB79gQZfeCAaqu8UhKgMcEtZuWoXtNkUyZuiYiAmefRPEEsG8Lfyz8aYnjMEEDIChdB/bC8ULLrpbeHhlsHEROqFEjDl2W5+hGRjPYkDelxgsi3EQWcjyJORd/RMK+45E=,iv:fowAvHutWKmEG1ts8jNjdYzfhALac9FuHuEd+Stv/1Q=,tag:UHTJiXYRAdKM7yIN3lacVw==,type:str]
    version: 3.13.2
