apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Ynr9piEH3r/svxZQ0GjHkMRK6ij1czpGkTMiyDy+EYMZO5j5lj6q4gFT87xUjpH+fy1Fsdg=,iv:o/twWFMHdFiEzd8J98mF4CbidbD8oqjBnlnykU1y0Ps=,tag:/P76m4x5OtmZP45WNWXg0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGhJMWE2aURuczdFVmNn
            Q3JUeGlMVVBCLyt5b1l1d2xDUUhtb3hMY3kwCnhaWllQam9sWFA4NlJVMkZmcE5B
            akhrUjBWZms1VzhVbjNJd0IweEtMSm8KLS0tIHRZYS9JVDNIeGw3UlBBeE4rVUZP
            azZUUnZyZEtEb1phL3JzS09GTXBCQUUKNcv1j1fkzaZfvcVIR9XzT7B2Hd4WMLd6
            0iDdipBlP4isCzj3EASs2rIdABpFXAv+NvIRwL885UyQCL0/90zpbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T03:59:18Z"
    mac: ENC[AES256_GCM,data:Z4ZsDg+vmKJXwUl+FALFTfZ2HSeJwvOcfP0X8iPzNl0kiqcJGcwv6Pi2ngYk5FjynzEfXkGDINmkm5Rxfk1Jw6PsJKhr+q0DzVy1PYjf9ZHUlpvlugaRVKXsryBepncCZifU+SMVtBrliUU6AKBFzFJJJeqfmvyHW5zixnw0I6c=,iv:l0GzRMpAjBuuJ42vlhaAS7VcTbn6B6E9n/ZGgpHItjo=,tag:5IsDPwBCIHh9FZ+wnAwCZQ==,type:str]
    version: 3.13.2
