apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:woEOrbWNQ7FNpivHDGDmuybXGA2uPZ0AaomZdpwtixs61aplF3OFCPUSh4lKzNbur7LXPWYWDo8q5ZC4yVFGl9sRf1GNIkFQiI3iOk9qo5TgkmqiLz3STZ7mkqW8ApilZgcShT957URGDlRW2e51SLlKRLvMxoxgRqlqtUc8tqGaFuBJyzMQ+ej0kKGV7Cpbe9BKDEnfgRqV+BtPFkqchktsNTKvtssb/Qr6OjvTPL7KLlCx0rVIBg==,iv:au+QW1gfD9NRePof446g3JIVepvlCxIJFSqEsBhtcWs=,tag:FiOp7gonQ2NWUsEck3qNuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN0JmZS9nYlgzcVJxU2cr
            MkhvWkV4aWVEMWp5QlJGZXczM2ZHcWpiMjNFCkh6b2pDM0xaZHI3ZDNpT0dVU1ZC
            Y0hvUnljSHRURDN1TERYRHI4cWswdFkKLS0tIG5IQlpNY2wyL0ZBVEhFTlQxU3NL
            Nmt4cWtFeWljb1pkNFV0N25SNzVhRjAK3fBPpr0AbYNRyAS1kWMVJZgvQ/IyFguH
            c24KQ4wizQhSRj2w9xx9NvNOWnTIJj14P+9umBluvzH4UpQLCgCwJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T22:39:06Z"
    mac: ENC[AES256_GCM,data:kBk8p7dWR4JtilUFNGOsXWVchhemXyV3KxksXDN1gkBLgYa6ypnd8uA61C7w2PtqZb399MdFWMJifLRsiRc2PWVeo25QaEnZDmvB3kiwUodmF3z5bb9w6KnGcj8O/p7Y0S/HeOXPVPMmG/bYc265YpcJ6aEgNngpcTQJxd8I4YE=,iv:6Y5i8Y+fH/jSgjNCOnGYXuxkgcINbOtzJjk1F1j515k=,tag:FPAu90L1NSy+3q39G1sTKQ==,type:str]
    version: 3.13.2
