apiVersion: v1
kind: Secret
metadata:
    name: rfc2136-keys
    namespace: external-dns
type: Opaque
stringData:
    rfc2136-tsig-keyname: ENC[AES256_GCM,data:v393+ByyJWkf4PfsMmdY,iv:sGdNUynhWZ3WgFn7J9VAZ5n4627L5vpkxvCOugRBVSA=,tag:NiW0DRPuNwgdFQ+68RjAJA==,type:str]
    rfc2136-tsig-secret: ENC[AES256_GCM,data:nhabpDu8G6P8wCoZI5we62aZnCslc+uM3alFY7lrU9CzeA7gGCT+1da9xhg=,iv:C4ybreD8ShTYdWOszqIgRhGj2o3oOu0TN6FigxPkcwk=,tag:52+bTVx3AaWGsZZys23Pxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdzAzdkoyODJzS0duM1Uy
            Wkd1UnlCYlcxMGlIb0wyUHhBU3VPZmtUOVd3Cld3SEpidEE2NDk3MnAvdFR3NVRs
            THZ3dHpDVU5oQUIvRmJHa3ZJOHo4WkkKLS0tIGF2M2QzU0NXMlBndzFjYXhFZUN0
            NzdHeGZtOGhzNUEwdXB6RXRUUDNrUmcKhMmrNz2p9Vimkh0sSy8qI9DfIIMmOFg/
            YfLqdGZuOr7VlbQJqDFqPlK4EvRy6ZvlmALkYyOdF6G9031fM30guQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T03:38:35Z"
    mac: ENC[AES256_GCM,data:Ot6TiSGDvOf09Mr1j8BKqsOhDj40ndAemY1bUo3w2OKAQVyvWoYBjfT6t3FI1798MYn/Lo1ITK8Zd/fEEKqildcKnZDmujZil1EyEKn1as2UP51YiWnrGb7hAqgaSNBT1/9zL3cuBoJsgH7QLlRqi4cDIiKdiJgRbL7TtWAUs5s=,iv:VrHrmj/BdiQlfR+xmp41SzibRmDKGFygf5x9JdyJXTw=,tag:p/mWZauH4NRCYLgLfpQ70g==,type:str]
    version: 3.13.2
