apiVersion: v1
kind: Secret
metadata:
    name: rfc2136-keys
    namespace: external-dns
type: Opaque
stringData:
    rfc2136-tsig-keyname: ENC[AES256_GCM,data:3HFl9T2h4EFHWv7R,iv:GBfmBVrt60HpgARGCbvR4Pgmz/r2yQAsf9ETuMXn/DM=,tag:fEEfn2wTe7LVabp/KQcmaQ==,type:str]
    rfc2136-tsig-secret: ENC[AES256_GCM,data:E6bQBeFg5rNQUChwwdAG4pCcbDB4YBAdXPp+pL8pwpP2P5sOtt7qc6d2ips=,iv:ftpp6AFyn8Xx0NetHsIBB4LG5HwI+aExVgEi8K2NH14=,tag:UTwMB3Wkj3ppnkhhlEVEKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aVkyeVdkdy9QNDRoVEJW
            SkxEZ2pSdnNtV3VZQWFwc0Z2cm1CWWNCQnhzCitRc1R4Z2hyWU0weGowVUhqZW9P
            bGVtNGJYNTE0YlJEemVGUWtnV1Q5OTQKLS0tIHkwOXM4SHRvZytrWFNTUTc3KzFv
            aEdxTTVNK0EyclRUNEtRd1l5OGl2bm8KVZhwvrOIqUF7POq86blYSxf8NQ7e8V2h
            yx5ja7PTvTkYRWOzJLQ/rXETL0Dro0sI+0uXSieYuy68Xdzy1TfXBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c00k2slacvsm6ntjdl0fp7u6qr882zr257yxqeqt9adqqqmuef9qnnx6zz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T01:49:06Z"
    mac: ENC[AES256_GCM,data:EOMkvBK77Rjhy1+veURKc3ub0+JTiZlcGUYA6qX7wrjduGwsytba8i92LEotWcriLYS5DKib7L+9u2vr1gm+AfVxS+MKB2mDIN1BUItBEYu+jEx1LQ8OuiMLS23GunC1vcrgyKwdvUpwIBHGJw3ms6f5VT1dqIxAb1rtPAr4CeY=,iv:szMXz0nedv7Bhn92TX3hIocoWPUcl5jcmxLLRG5adrc=,tag:f9Q2//gAOTNZ0yElierD4g==,type:str]
    version: 3.13.2
