apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/cert-manager-operator
  - ../base/cert-manager-configs
  - ../base/cnpg
  - ../base/external-dns
  - ../base/cilium-gateway
  - ./cilium-gateway
  - ./traefik
  - ./storage