apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/cert-manager
  - ../base/cnpg
  - ../base/external-dns
  - ../base/traefik
  - ../base/cilium-gateway
  - ./cilium-gateway
  - ./traefik
  - ./storage