# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: cert-manager
#   namespace: cert-manager
# spec:
#   interval: 1h
#   url: https://quay.io/jetstack/charts/cert-manager # or oci://registry-1.docker.io/bitnamicharts/cert-manager

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  url: oci://embed.quay.io/jetstack/charts/cert-manager
  ref:
    tag: v1.21.0 # 'ref' is valid on OCIRepository