apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-client-values
  namespace: nfs-provisioner
  labels:
    app.kubernetes.io/part-of: nfs-client
data:
  values.yaml: |
    nfs:
      server: 192.168.75.250
      path: /volume1/k8s
      mountOptions:
        - nolock
        - nfsvers=3
        - tcp

    storageClass:
      create: true
      name: ugreen-nfs-sc
      reclaimPolicy: Retain
      archiveOnDelete: true
      allowVolumeExpansion: true
      accessModes: ReadWriteOnce
      volumeBindingMode: Immediate
