apiVersion: v1
kind: Secret
metadata:
    name: backblaze-b2-creds
    namespace: vaultwarden # Replace with your CNPG cluster namespace
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:SaUoc3vaCr4xLwxGt7rHu4IroEkg5p1+Lg==,iv:thjZvKm7QSercQV0n6SPSDmQEgGYtSYoUKCs4YoAZQ4=,tag:NkDG6Q3uP+OpxvbbczRRUg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:cPjDzjGPhgaGDvyAoSGZw4F0x+CxckxN8QZNDD8CRg==,iv:fBSem4ciRsd/lFCAgQDJVb3Ku6AwxONulnq8D29lHE4=,tag:8a6GOPsgJmEknTYtfIZ61A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZE9QeDRGSGw2bmtFaHFY
            bExjYW12d3VtQ0ZFZDhrQXl0bGcwb1Y4emlFCkNsdjRFT0VHQTRnT0t6azZLTXFW
            ell6emIrNnJyUHNSVkk1cU5qcG5pQ28KLS0tIFE3RGs5ck1PdGM4ZTdySVZ1Mld4
            VkFjd0szU0NwbHFGOFUzbUhMQ1ZTRE0KMCldHe0RUGHWzFqFB9dOouhZfOBLbjA7
            gk+yZ97KmdCDQjnFTmreXH0N+88s0T3EfqKyFUk6kKSM3mwtgijYuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:11:44Z"
    mac: ENC[AES256_GCM,data:ySQqKy+0uG/+7it//KQpc3suoyj4WHiC4lnlpkCKy8L3gtrJoyjhRcag4yvrdeXVNBgUtFq+B0GQoej72xydxrzZG5/g1LCzj2J8GUuIJq9AX9Onm0h0agp5vEskw16OJSTi6oP82DKMHucjSfR8KkIeVIRDylTHLt3dMMhU9Ks=,iv:mX8iymVOOyfzB+nd1mnZLnDlwD2UC7vB7cchYqOYwhI=,tag:BVM2mIvpdfAI1fOouCxJag==,type:str]
    version: 3.13.2
