apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-infra-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  path: ./infrastructure/crds/gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-infra-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  path: ./infrastructure/secrets/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: production-infra-crds
    - name: production-infra-secrets
  interval: 10m
  retryInterval: 2m
  timeout: 10m
  path: ./infrastructure/production/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: production-infra-controllers
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  path: ./infrastructure/production/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true