apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared

data:
  config.yaml: |
    ingress:
      - hostname: vaultwarden.tmatthews.casa
        service: https://192.168.40.3
        originRequest:
          originServerName: vaultwarden.tmatthews.casa
          noTLSVerify: true

      - service: http_status:404