apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared

data:
  config.yaml: |
    ingress:
      - hostname: vaultwarden.tmatthews.casa
        service: https://traefik.traefik.svc.cluster.local:443

      - service: http_status:404
