apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-db
  namespace: firefly
spec:
  #imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixi
  instances: 2 # Set to 2 or 3 for high availability (primary + standby replicas)
  
  # Storage configuration
  storage:
    size: 5Gi
    storageClass: local-path # Adjust to your RWO storage class

  # Database initialization defaults
  bootstrap:
    # recovery:
      initdb:
        database: firefly
        owner: firefly
        secret:
          name: firefly-db-secret # Secret created by CNPG holding database credentials
      # source: firefly-backup-pitr             # externalCluster name, defined below

      # recoveryTarget:
      #   targetTime: "2026-08-24T10:58:00"
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: firefly-b2
        serverName: firefly-db         # NEW clean identity going forward distinct name for the PITR cluster, used to store WAL files in B2 bucket

  # externalClusters:
  #   - name: vaultwarden-backup-pitr
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io

  #       parameters:
  #         barmanObjectName: vaultwarden-b2
  #         serverName: vaultwarden-postgresql-pitr     # read from the LIVE cluster's backup
