apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:aLwVYmGzPcxJuaY=,iv:7AFbKxJPpLOjwkQQ4kDaQeFpMhphS4vW6geiYYFp3lQ=,tag:jmIPAtAWU8PSkolzT267uw==,type:str]
    password: ENC[AES256_GCM,data:r2ZyyYorTcQiCZ2fpz8=,iv:vpbSFSnjO7o8dxZHtK31sWT7u81ympUf6YuwaUMFR4E=,tag:PF3K9joD/upP8eewpDZtmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbjMrejQ3Uld2UldIeExK
            WC93Vjlxa1pZbDR2S3hGdUEzVHpZTnZRWDJVCi8rK2dPbjFiOW14cHVka0pDa0Fz
            OUxYR1VNeXJGaGtvOE9pN3o2TUlBOG8KLS0tIHo5Tmh2SGVTV01HYzFMK1U0Njlq
            S0RDekp4V21aRFAvT056MnZIWjIrakkKgoNi58f4bMPYVnRJs0G7xaX6UjQx4yhR
            JPQVV6HA9iJqJXNRuyjt3GVOiGeqZXZnJM6DXQ8J5l+ggdXRGT3Krg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T20:44:00Z"
    mac: ENC[AES256_GCM,data:EIYNufjFQbc1xuYAw+u+SEv3hs4JVU6XdCZizbkEI2rxdhWHyZmB4P9W1/gQHRJI+KQ+OelfLgX9M4ScvGhD4dpARR4AFU00h7P9rdV8qzQb7SFFA2/VX00zzcVFc+sRDhJcATpl2b1dWfSFr5uFCgmbV3+mh1VZbJXQYxuN9Zw=,iv:dnEgrZ0UKnhUCs9zBdH/SxKOghDxaHTVbjWFMUhgfKw=,tag:AXWZHEeIggLT26lZaN8BrA==,type:str]
    version: 3.13.2
