apiVersion: v1
kind: Secret
metadata:
    name: firefly-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0cKdEb7Whg==,iv:Zm5dqhasP9bC5l0WsDuNEQiyh3Su4EwSNIzYJZok8Aw=,tag:y1rT/heDbmN2laI09cnW8A==,type:str]
    password: ENC[AES256_GCM,data:LtRUNTCuOTHAKPC/PIY=,iv:ou79ZOeToukxGUmgnUqiYbqClSG2kBe24Lxk0uvGJ5U=,tag:/fa/XT0M665koRO3tqLk1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTXBlUnNGSGZmbnJoWVNi
            NEpPV25CY01aQkhSNldNL1JMRmRFSVNsZ0dZCjZ0UlVOZEZMajNKK3IrOVZaZ2l3
            UDNXVWt3VDJaMHBySjBCQkJKQlhERGsKLS0tIE5LWWpSQis1SGJzeVdLSE1xQXY5
            Nnl3dDB3c2l6K05ocnpldDdvWHlKelkKXGbtrZrDODIUOWkmIqnxMS5iTKY1kwZz
            WMwQ/3CbuCr0atuaRwqcHuuAtHVP2oFv7I8UY1kL2saNVQwMgIkkqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T04:39:26Z"
    mac: ENC[AES256_GCM,data:RyqdDsSlws+qGYVIigujpBSjXYrQSgvxzt7l67vQy2YwxE8UF3GzIdVUPk0aKajLmiY0LeTfzUzgX8IzTZ4og/13tzJJwRUDVS0QbFRflXLGG5IWvlQvxAI8LIWHVgZzR2K3N/Jzm/yOlz9tRgoHxJzuMg1mdwyM27vxInhCOng=,iv:QqdpPWObb0lJ/WP0t/GtzG4qtfSrjO3fATlSi6PWvac=,tag:Ks7sr3JLMWUjwi68RULX1g==,type:str]
    version: 3.13.2
