apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly

resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - firefly-app-secret.yaml
  - firefly-db-secret.yaml
  - firefly-dbcluster.yaml
  - backblaze-creds.yaml
  - backblaze-store-object.yaml
  - httproute.yaml