apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls-cert
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls-cert
  dnsNames:
    - "*.tmatthews.casa"
    - "tmatthews.casa"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer