apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app-vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vaultwarden.tmatthews.casa`)
      kind: Rule
      services:
        - name: vaultwarden-svc
          port: 80
  tls:
    secretName: vaultwarden-tls-cert # Keep this empty. Traefik automatically applies the default TLSStore.
