apiVersion: v1
kind: Pod
metadata:
  name: mtu-vlan75-p02
  namespace: mtu-test
spec:
  hostNetwork: true
  nodeName: k8s-crtl-p02
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]