# -- Additional command arguments to be passed to all traefik's pods

additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--api.dashboard=true"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  revisionHistoryLimit: null
  terminationGracePeriodSeconds: 60
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: "kubernetes.io/hostname"

  readinessPath: "/ping"
  livenessPath: "/ping"
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  initContainers: []

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
      pathOverride: "traefik/traefik"
  kubernetesGateway:
    enabled: true
    statusAddress:
      service:
        name: traefik
        namespace: traefik

log:
  level: "INFO"

gateway:
  enabled: false

gatewayClass:
  enabled: false

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
  
  websecure:
    asDefault: true
    port: 8443
    expose:
      default: true
    exposedPort: 443

autoscaling:
  enabled: false

# persistence:
#   # -- Enable persistence using Persistent Volume Claims
#   # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
#   # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
#   enabled: true
#   name: data
#   accessMode: ReadWriteOnce
#   size: 128Mi
#   storageClass: ugreen-nfs-sc
#   path: /data

# -- If hostNetwork is true, runs traefik in the host network namespace
# To prevent unschedulable pods due to port collisions, if hostNetwork=true
# and replicas>1, a pod anti-affinity is recommended and will be set if the
# affinity is left as default.
hostNetwork: false

# -- Whether Role Based Access Control objects like roles and rolebindings should be created
rbac:  # @schema additionalProperties: false
  enabled: true
  # When set to true:
  # 1. It switches respectively the use of `ClusterRole` and `ClusterRoleBinding` to `Role` and `RoleBinding`.
  # 2. It adds `disableIngressClassLookup` on Kubernetes Ingress with Traefik Proxy v3 until v3.1.4
  # 3. It adds `disableClusterScopeResources` on Ingress and CRD (Kubernetes) providers with Traefik Proxy v3.1.2+
  # **NOTE**: `IngressClass`, `NodePortLB` and **Gateway** provider cannot be used with namespaced RBAC.
  # See [upstream documentation](https://doc.traefik.io/traefik/providers/kubernetes-ingress/#disableclusterscoperesources) for more details.
  namespaced: false
  # Enable user-facing roles
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  aggregateTo: []
  # List of Kubernetes secrets that are accessible for Traefik. If empty, then access is granted to every secret.
  # secretResourceNames: []

service:
  enabled: true
  type: LoadBalancer
  single: true
  externalTrafficPolicy: Local