apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - local-path-provisioner.yaml
  - nfs-client.yaml
  - nfs-client-values.yaml
  - traefik.yaml

configMapGenerator:
  - name: traefik-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=./configs/traefik/production-traefik-values.yaml