apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:TZB7eyPDDhq5q6W1T/Iy/mGViAfaQN4aruBj5hwayMYmr43nFFEBGRF3JBsrdxA4W8VHBCtrrwRPmVEoG1olNDkNZVXBa9ZUTR+p3gTtM6izgnBxywEs+FZsPGh2h6d0MT7rjjqA9fEVtkyIGh+mg70gq2ccAPwr0UomYPibvofhFrdJ3oJI3SP2+Q4IEE8TMTBlaCoebf1JjdL3UrBmznLhoxlI8QZ0Lex4iOszB4EFf9/J,iv:03E0Ns63BeqAHc9qQ+lDHsD4q9B9vbKkPG5jqrkZeRQ=,tag:zrQ8O55HK6UbHvG0+rGn1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVUthZFA3TlZaclRqeU9a
            M1FlQXp0YkdJVzluTkZpeXhpZHExQ01mS1JjCjE3NzBJRUlRRkh4QVNnMVkvYk42
            WkZ0UHllL3FTOUZ4ZDhmNkZnMXdMazAKLS0tIGR2emZuZVorTFhybWowT29sdUMv
            YThLWUFudi9OMkRjd2wyWktJZWE2SVkKessDA9RlDZ2XzdPyx5hXWKlEEfHZ+UP/
            v4ltNRiTChoOK4yvjFoxSqoX5YoMZRVkAYBzyMK6SpuktxpDifKorA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T03:51:45Z"
    mac: ENC[AES256_GCM,data:PUmBYp9GYKB5THX0CVFSOz8Vc9UjhUkT8NnBhWcErdpAxfiS74XtdQa1bTsgWBHQTyB+IA0O3remQaUOYteCkK9P0KNvCQcqVH8X0bzx4PGSweLzSofiXNSP2KyRcYjMacVp2DOQ2SQeCYJJARaLQvtT0eKZuJdJynkcGIJr2BE=,iv:vYwg1ZwkwNXM/YlWCVvF8vpAKZNbksg1exz2nBjm4Xs=,tag:VkYeGF28L75at8b9ELwkIw==,type:str]
    version: 3.13.2
