---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: whereabouts
  namespace: kube-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/k8snetworkplumbingwg
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whereabouts
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: whereabouts-chart
      version: 0.9.4   # e.g. from: helm show chart oci://ghcr.io/k8snetworkplumbingwg/whereabouts-chart
      sourceRef:
        kind: HelmRepository
        name: whereabouts
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace