apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+7OWReDMNf2KKjcN7TKSpUW3e2s8LJJGTQe+taUbRbm6b+pQmlj7BoRBRa9rLf4B2tdJ8XA=,iv:zH4Dk3vSSEwhxsPQqklM4LuaGft3Do47CWG07WkZCoU=,tag:260yH3hp7cSvR5h671KNdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U1YwNy9qNVFiN1RUNzc5
            K214OStqQ0FlRVdZUi9SUUhFTGN5YzdMWXlrCmNwalh3Ulhnd1NQWEdUSURieDhP
            OHc2dDN1blUrbklQdFdFdTJhVDNIZXMKLS0tIE94dHNpcXUwSVF2eUp0UlRLUHpv
            bm4yYW5zdXRvZjFyNVI5MjdKREN5RVEKq6epwL9CBnSEx34Bp8y2TIxToxT1I3m6
            5vY0NQUDoOhcQBxp9Teffi40eSp+7qVugoar/elSOU2zHQsgqHiTaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T00:57:10Z"
    mac: ENC[AES256_GCM,data:U7c5CyvQEaJJiAbZ9+ahdn2ZjpgCXcjrowejA4O0Q7J4WnxN5MwOzW2CAXTE50AUdQCjwxaROXUJLFiY0IlRV/4zYbkO0If5XTJS3+QMl0SwncrVoOGhqhSzLm/zMlvx49axRjxpImfozHzNpWloRbtZKoYmdETAUB4ZFmV/lUs=,iv:qgmMLp08eF0ml/KTDrfuJBIGrmNZTydysWngO6wiPDI=,tag:LZ8LoLG+kOZ5XA/fOLdEQg==,type:str]
    version: 3.13.2
