apiVersion: v1
kind: Secret
metadata:
    name: rfc2136-keys
    namespace: external-dns
type: Opaque
stringData:
    rfc2136-tsig-keyname: ENC[AES256_GCM,data:ar1tvCe1KYOC3iV2,iv:/lqZFhxJu+I2uwfzS+8VGM6MseKm3VMOVW0lf7p4SYw=,tag:R/9DkcD2cnMZuy10P2rwpg==,type:str]
    rfc2136-tsig-secret: ENC[AES256_GCM,data:z9NCgM3oQFHDx2o4bQdQLju1KEZJzCVSq4JIPmcyRpPJkZ9AE+Z+9iJfByA=,iv:Jdloai69QtBPB5Yj9mzqA5vh1Bl9plXKebDsvcfChpM=,tag:NMMn3JVUugfwmdWp3PDvTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOVN6NmZRTHBTSVdUL0Zo
            aDBaQVpOdVFMZVBHdmNaZkVoWStQOURvNlMwCmxMYUt1dUtWRjFGUlVDVndVR2Fn
            VTQyRnJDRFNZNHZQVzd3MG1ES2Y2cjAKLS0tIGJRa3ExaGtXek9ncXJCQVpkRjZ5
            QVd3NGNJUkVyY0ZybEhvbzN5S3N0QmMKizqFiPtAPjHKugBWje6aX++aCy9Iftcq
            ffKDsJLBhzF9jWIaaid92pUHKF2dWKEcmow7R9vMYZ5jebAQ4Q+oEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19juhr3umucask0st9rncphwmgvuwlgwr7cyclyuahlpt5q65gussg93zec
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T00:56:54Z"
    mac: ENC[AES256_GCM,data:JKbNuS17x9M23BmP1wRheh87mnQdSh7iQgcYr5HWU7GjBDdurL26cGdos003A6iLazfGzRVuGsgPBzKKkVJ4hslx0F7ntDYNTr+GP7l2S9JUJekHyaD4CrnVSJkDgufwNdmP2pKyaqdV+nmjFPM4YiWjD8JRcL0YcYN9IKYh+2E=,iv://8RzgElqrY9bXcWemBUoU9KuC+fuU+GmD5elTt3pdM=,tag:BFlDhiYigHbL7/6BLWfSPw==,type:str]
    version: 3.13.2
