apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../configs/base/traefik
  - dashboard-ir.yaml

patches:
  - path: helmrelease-values-patch.yaml

configMapGenerator:
  - name: traefik-production-values
    namespace: traefik
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml