---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/migration/multus
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whereabouts
  namespace: flux-system
spec:
  dependsOn:
    - name: multus
  interval: 1h
  path: ./infrastructure/migration/whereabouts
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-network
  namespace: flux-system
spec:
  dependsOn:
    - name: whereabouts
  interval: 1h
  path: ./infrastructure/migration/longhorn-network
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-network
  interval: 1h
  path: ./infrastructure/migration/longhorn
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system